/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ButtonAddOrder: typeof import('./src/components/business/ButtonAddOrder.vue')['default']
    ButtonBecomeSitter: typeof import('./src/components/business/ButtonBecomeSitter.vue')['default']
    ButtonRequestWechat: typeof import('./src/components/business/ButtonRequestWechat.vue')['default']
    ButtonShowDetail: typeof import('./src/components/business/ButtonShowDetail.vue')['default']
    CommonList: typeof import('./src/components/common/CommonList.vue')['default']
    IconCat: typeof import('./src/components/icons/IconCat.vue')['default']
    IconDog: typeof import('./src/components/icons/IconDog.vue')['default']
    IconFemale: typeof import('./src/components/icons/IconFemale.vue')['default']
    IconMale: typeof import('./src/components/icons/IconMale.vue')['default']
    IconUser: typeof import('./src/components/icons/IconUser.vue')['default']
    LocationSelector: typeof import('./src/components/common/LocationSelector.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutInputNumber: typeof import('@nutui/nutui-taro')['InputNumber']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutSpace: typeof import('@nutui/nutui-taro')['Space']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    OneLineTags: typeof import('./src/components/business/OneLineTags.vue')['default']
    PetOrderCard: typeof import('./src/components/business/PetOrderCard.vue')['default']
    PetSitterCard: typeof import('./src/components/business/PetSitterCard.vue')['default']
    PopupOrderForm: typeof import('./src/components/business/PopupOrderForm.vue')['default']
    PopupSitterForm: typeof import('./src/components/business/PopupSitterForm.vue')['default']
    TagsSelector: typeof import('./src/components/common/TagsSelector.vue')['default']
    VirtualListAdapter: typeof import('./src/components/common/VirtualListAdapter.vue')['default']
    VirtualListItemAdapter: typeof import('./src/components/common/VirtualListItemAdapter.vue')['default']
  }
}
