/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonList: typeof import('./src/components/common/CommonList.vue')['default']
    IconCat: typeof import('./src/components/icons/IconCat.vue')['default']
    IconDog: typeof import('./src/components/icons/IconDog.vue')['default']
    IconFemale: typeof import('./src/components/icons/IconFemale.vue')['default']
    IconMale: typeof import('./src/components/icons/IconMale.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    PetOrderCard: typeof import('./src/components/business/PetOrderCard.vue')['default']
    PetSitterCard: typeof import('./src/components/business/PetSitterCard.vue')['default']
    VirtualListAdapter: typeof import('./src/components/common/VirtualListAdapter.vue')['default']
    VirtualListItemAdapter: typeof import('./src/components/common/VirtualListItemAdapter.vue')['default']
  }
}
